name: stream_chat_flutter_core
homepage: https://github.com/GetStream/stream-chat-flutter
description: Stream Chat official Flutter SDK Core. Build your own chat experience using Dart and Flutter.
version: 8.0.0
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  collection: ^1.18.0
  connectivity_plus: ">=6.0.5 <7.0.0"
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  meta: ^1.12.0
  rxdart: ^0.27.7
  stream_chat:
    git:
      url: https://github.com/pgahq/stream-chat-flutter.git
      path: packages/stream_chat
      ref: android_compatibility_8.0.0

dev_dependencies:
  build_runner: ^2.4.11
  fake_async: ^1.3.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  mocktail: ^1.0.4

